vpcs:
 - name : "main-v"
   cidr: "10.0.0.0/16"
   max_azs: 2    
security_groups:
  - name: "sec-group-1"
    service : "main-v"
    ingress_rules:
      - cidr: "10.0.0.0/16"
        description: "Allow all traffic within VPC"
        port: "ALL_TRAFFIC"
vpc_endpoints:
  - service: dynamodb
    name: "TestEndpoint"
    vpc: "main-v"
    subnets:
      - "PRIVATE_WITH_EGRESS"

iam_permissions :
  - name : "dynamoDB_Perm"

    policies:
        - action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
            - cloudwatch:PutMetricData
            - ec2:DescribeVolumes
            - ec2:DescribeTags
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - logs:DescribeLogGroups
            - logs:CreateLogStream

            - logs:CreateLogGroup


asg:
  - name: myasg
    policy : 
      - "dynamoDB_Perm"
    vpc : 'main-v'
    user_data_path : 'code-app.sh'
    max: 3
    min: 1 
    policy :
     - "dynamoDB_Perm"

alb:
  - name: myalb
    vpc : 'main-v'
    asg: myasg

dynamodb:
  - name: "TestTable"

  

          
