vpcs:
 - name : "main-vpc"
   cidr: "10.0.0.0/16"
   max_azs: 1
   subnets:
    - name: "public"
      type: "PUBLIC"
      cidr_mask: 24
    - name: "private"
      type: "PRIVATE_WITH_EGRESS"
      cidr_mask: 24
security_groups:
  - name: "sec-group-1"
    description: "Default VPC security group"
    service : "main-vpc"
    allow_all_outbound: true
    ingress_rules:
      - cidr: "10.0.0.0/16"
        description: "Allow all traffic within VPC"
        port: "ALL_TRAFFIC"
vpc_endpoints:
  - service : dynamodb
    name : "TestEndpoint"
    vpc : "main-vpc"
    subnets:
      - "PRIVATE_WITH_EGRESS"